root: true
env:
  browser: true
  es2021: true
extends:
  - next/core-web-vitals
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
rules:
  react/react-in-jsx-scope: off
  '@typescript-eslint/explicit-module-boundary-types': off
  'import/no-anonymous-default-export': off
